console.log("model.js is loaded!");

"use strict";

/* ====================================================================
 Copyright (C) 2022 JMP Statistical Discovery LLC. All rights reserved.
 
 Notice: The following permissions are granted provided that the above
 copyright and this notice appear in the score code and any related
 documentation. Permission to copy, modify and distribute the score
 code generated using JMP (r) software is limited to customers of JMP
 Statistical Discovery LLC ("JMP") and successive third parties, all
 without any warranty, express or implied, or any other obligation by
 JMP. JMP and all other JMP Statistical Discovery LLC product and
 service names are registered trademarks or trademarks of JMP
 Statistical Discovery LLC in the USA and other countries. Except as
 contained in this notice, the name of JMP shall not be used in the
 advertising or promotion of products or services without prior
 written authorization from  Statistical Discovery LLC.
 ==================================================================== */

/* JavaScript code generated by JMP 17.0.0 */
var getModelMetadata = function() {
return {"creator": "Neural", "modelName": "Model NTanH(3)NLinear(3)NGaussian(3)NBoost(2) - Save Formulas", "predicted": "Clinical Trial enrollment: (Yes=1, No =2)", "table": "Paper shap values External validation dataset-updated714 1.jmp", "version": "17.0.0", "timestamp": "2025-02-02T18:41:31Z"};
};

var getInputMetadata = function() {
    return {
   "$schema": "http://json-schema.org/draft-04/schema#",
   "id": "/",
   "type": "object",
   "properties": {
     "Age.at.Initial.Diagnosis": {
       "id": "Age.at.Initial.Diagnosis",
       "type": "number"
     },
     "Employed(Y=1, N=2, Retired=3) 2": {
       "id": "Employed(Y=1, N=2, Retired=3) 2",
       "type": "number"
     },
     "Ethnicity Hispanic/Latino (Yes=1, No=2) 2": {
       "id": "Ethnicity Hispanic/Latino (Yes=1, No=2) 2",
       "type": "number"
     },
     "KPS.post.op 3": {
       "id": "KPS.post.op 3",
       "type": "number"
     },
     "New Tumor Lobe (updated chart review) 2 2 2": {
       "id": "New Tumor Lobe (updated chart review) 2 2 2",
       "type": "number"
     },
     "Reordered insurance at diagnosis 2 2": {
       "id": "Reordered insurance at diagnosis 2 2",
       "type": "number"
     },
     "Seizure.preop 2": {
       "id": "Seizure.preop 2",
       "type": "number"
     },
     "Sex (M=1, F=2)": {
       "id": "Sex (M=1, F=2)",
       "type": "number"
     },
     "TMZ anytime 2 2": {
       "id": "TMZ anytime 2 2",
       "type": "number"
     },
     "Updated Race White, Black/African American, Hispanic/Latino, Asian/Pacific Islander, American Indian/Alaska Native 3 2": {
       "id": "Updated Race White, Black/African American, Hispanic/Latino, Asian/Pacific Islander, American Indian/Alaska Native 3 2",
       "type": "number"
     },
     "WHO Grade 2 2": {
       "id": "WHO Grade 2 2",
       "type": "number"
     }   },
   "additionalProperties": false,
  };
};

var getOutputMetadata = function() {
    return {
   "$schema": "http://json-schema.org/draft-04/schema#",
   "id": "/",
   "type": "object",
   "properties": {
     "ProbabilityEnroll": {
       "id": "ProbabilityEnroll",
       "type": "number"
     },
     "ProbabilityNotEnroll": {
       "id": "ProbabilityNotEnroll",
       "type": "number"
     },
     "MostLikelyClinicalTrial": {
       "id": "MostLikelyClinicalTrial",
       "type": "number"
     }   },
   "additionalProperties": false,
  };
};

var score = function(indata, outdata) {
   console.log("✅ model.js received input:", indata); 
 // Original name was: 'WHO Grade 2 2_asCode'
    var WHO_Grade_2_2_asCode;
    // Original name was: 'Updated Race White, Black/African American, Hispanic/Latino, Asian/Pacific Islander, American Indian/Alaska Native 3 2_asCode'
    var Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode;
    // Original name was: 'TMZ anytime 2 2_asCode'
    var TMZ_anytime_2_2_asCode;
    // Original name was: 'Seizure.preop 2_asCode'
    var Seizure_preop_2_asCode;
    // Original name was: 'Reordered insurance at diagnosis 2 2_asCode'
    var Reordered_insurance_at_diagnosis_2_2_asCode;
    // Original name was: 'New Tumor Lobe (updated chart review) 2 2 2_asCode'
    var New_Tumor_Lobe_updated_chart_review_2_2_2_asCode;
    // Original name was: 'Minority (Yes=1, No=2) 2_asCode'
    var KPS_post_op_3_asCode;
    // Original name was: 'Ethnicity Hispanic/Latino (Yes=1, No=2) 2_asCode'
    var Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode;
    // Original name was: 'Employed(Y=1, N=2, Retired=3) 2_asCode'
    var Employed_Y_1_N_2_Retired_3_2_asCode;
    var H1_1_1;
    var H1_2_1;
    var H1_3_1;
    var H1_4_1;
    var H1_5_1;
    var H1_6_1;
    var H1_7_1;
    var H1_8_1;
    var H1_9_1;
    var H1_10_1;
    var H1_11_1;
    var H1_12_1;
    var H1_13_1;
    var H1_14_1;
    var H1_15_1;
    var H1_16_1;
    var H1_17_1;
    var H1_18_1;
    var _temp_0 = undefined;
    var _temp_1 = undefined;
    var _temp_2 = undefined;
    var _temp_3 = undefined;
    var _temp_4 = undefined;
    var _temp_5 = undefined;
    var _temp_6 = undefined;
    var _temp_7 = undefined;
    var _temp_8 = undefined;
    var _temp_9 = undefined;
    var _temp_10 = undefined;
    var _temp_11;
    var _temp_12 = [];

    if (indata["WHO Grade 2 2"] === 0)  {
        _temp_0 = 0;
    }
    else if (indata["WHO Grade 2 2"] === 1)  {
        _temp_0 = 1;
    }
    WHO_Grade_2_2_asCode = _temp_0;

    if (indata["Updated Race White, Black/African American, Hispanic/Latino, Asian/Pacific Islander, American Indian/Alaska Native 3 2"] === 0)  {
        _temp_0 = 0;
    }
    else if (indata["Updated Race White, Black/African American, Hispanic/Latino, Asian/Pacific Islander, American Indian/Alaska Native 3 2"] === 1)  {
        _temp_0 = 1;
    }
    else if (indata["Updated Race White, Black/African American, Hispanic/Latino, Asian/Pacific Islander, American Indian/Alaska Native 3 2"] === 2)  {
        _temp_0 = 2;
    }
    else if (indata["Updated Race White, Black/African American, Hispanic/Latino, Asian/Pacific Islander, American Indian/Alaska Native 3 2"] === 3)  {
        _temp_0 = 3;
    }
    else if (indata["Updated Race White, Black/African American, Hispanic/Latino, Asian/Pacific Islander, American Indian/Alaska Native 3 2"] === 4)  {
        _temp_0 = 4;
    }
    else if (indata["Updated Race White, Black/African American, Hispanic/Latino, Asian/Pacific Islander, American Indian/Alaska Native 3 2"] === 5)  {
        _temp_0 = 5;
    }
    else if (indata["Updated Race White, Black/African American, Hispanic/Latino, Asian/Pacific Islander, American Indian/Alaska Native 3 2"] === 6)  {
        _temp_0 = 6;
    }
    Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode = _temp_0;

    if (indata["TMZ anytime 2 2"] === 0)  {
        _temp_0 = 0;
    }
    else if (indata["TMZ anytime 2 2"] === 1)  {
        _temp_0 = 1;
    }
    else if (indata["TMZ anytime 2 2"] === 2)  {
        _temp_0 = 2;
    }
    TMZ_anytime_2_2_asCode = _temp_0;

    if (indata["Seizure.preop 2"] === 0)  {
        _temp_0 = 0;
    }
    else if (indata["Seizure.preop 2"] === 1)  {
        _temp_0 = 1;
    }
    else if (indata["Seizure.preop 2"] === 2)  {
        _temp_0 = 2;
    }
    Seizure_preop_2_asCode = _temp_0;

    if (indata["Reordered insurance at diagnosis 2 2"] === 0)  {
        _temp_0 = 0;
    }
    else if (indata["Reordered insurance at diagnosis 2 2"] === 1)  {
        _temp_0 = 1;
    }
    else if (indata["Reordered insurance at diagnosis 2 2"] === 2)  {
        _temp_0 = 2;
    }
    else if (indata["Reordered insurance at diagnosis 2 2"] === 3)  {
        _temp_0 = 3;
    }
    else if (indata["Reordered insurance at diagnosis 2 2"] === 4)  {
        _temp_0 = 4;
    }
    Reordered_insurance_at_diagnosis_2_2_asCode = _temp_0;

    if (indata["New Tumor Lobe (updated chart review) 2 2 2"] === 0)  {
        _temp_0 = 0;
    }
    else if (indata["New Tumor Lobe (updated chart review) 2 2 2"] === 1)  {
        _temp_0 = 1;
    }
    else if (indata["New Tumor Lobe (updated chart review) 2 2 2"] === 2)  {
        _temp_0 = 2;
    }
    else if (indata["New Tumor Lobe (updated chart review) 2 2 2"] === 3)  {
        _temp_0 = 3;
    }
    else if (indata["New Tumor Lobe (updated chart review) 2 2 2"] === 4)  {
        _temp_0 = 4;
    }
    else if (indata["New Tumor Lobe (updated chart review) 2 2 2"] === 5)  {
        _temp_0 = 5;
    }
    else if (indata["New Tumor Lobe (updated chart review) 2 2 2"] === 6)  {
        _temp_0 = 6;
    }
    else if (indata["New Tumor Lobe (updated chart review) 2 2 2"] === 7)  {
        _temp_0 = 7;
    }
    New_Tumor_Lobe_updated_chart_review_2_2_2_asCode = _temp_0;
    }
    
    if (indata["KPS.post.op 3"] === 0)  {
        _temp_0 = 0;
    }
    else if (indata["KPS.post.op 3"] === 1)  {
        _temp_0 = 1;
    }
    else if (indata["KPS.post.op 3"] === 2)  {
        _temp_0 = 2;
    }
    else if (indata["KPS.post.op 3"] === 3)  {
        _temp_0 = 3;
    }
    else if (indata["KPS.post.op 3"] === 4)  {
        _temp_0 = 4;
    }
    KPS_post_op_3_asCode = _temp_0;

    if (indata["Ethnicity Hispanic/Latino (Yes=1, No=2) 2"] === 0)  {
        _temp_0 = 0;
    }
    else if (indata["Ethnicity Hispanic/Latino (Yes=1, No=2) 2"] === 1)  {
        _temp_0 = 1;
    }
    else if (indata["Ethnicity Hispanic/Latino (Yes=1, No=2) 2"] === 2)  {
        _temp_0 = 2;
    }
    Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode = _temp_0;

    if (indata["Employed(Y=1, N=2, Retired=3) 2"] === 0)  {
        _temp_0 = 0;
    }
    else if (indata["Employed(Y=1, N=2, Retired=3) 2"] === 1)  {
        _temp_0 = 1;
    }
    else if (indata["Employed(Y=1, N=2, Retired=3) 2"] === 2)  {
        _temp_0 = 2;
    }
    else if (indata["Employed(Y=1, N=2, Retired=3) 2"] === 3)  {
        _temp_0 = 3;
    }
    Employed_Y_1_N_2_Retired_3_2_asCode = _temp_0;

    if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 0))  {
        _temp_0 = 0.0126647781306242;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 1))  {
        _temp_0 = 0.309197965917001;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 2))  {
        _temp_0 = 0.669498828036753;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 3))  {
        _temp_0 = -0.991361572084379;
    }
    if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 0))  {
        _temp_1 = -2.11922104691318;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 1))  {
        _temp_1 = 1.03185006170909;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 2))  {
        _temp_1 = 1.08737098520409;
    }
    if (jmp.numeq(KPS_post_op_3_asCode, 0))  {
        _temp_2 = -0.128876200026177;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 1))  {
        _temp_2 = -0.418557414450321;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 2))  {
        _temp_2 = -0.607157784509385;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 3))  {
        _temp_2 = -0.254941401832939;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 4))  {
        _temp_2 = 1.40953280081882;
    }
    if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 0))  {
        _temp_3 = -0.522776551234792;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 1))  {
        _temp_3 = 0.518897799532632;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 2))  {
        _temp_3 =  0.590201639773282;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 3))  {
        _temp_3 = -1.54512163100576;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 4))  {
        _temp_3 = -0.161403267528235;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 5))  {
        _temp_3 = -0.524604515772703;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 6))  {
        _temp_3 = 0.460018344194363;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 7))  {
        _temp_3 = 1.18478818204121;
    }
    if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 0))  {
        _temp_4 = 0.0414587108932192;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 1))  {
        _temp_4 = -0.795725093058357;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 2))  {
        _temp_4 = 0.270277193512977;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 3))  {
        _temp_4 = 1.29427092128275;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 4))  {
        _temp_4 = -0.810281732630594;
    }
    if (jmp.numeq(Seizure_preop_2_asCode, 0))  {
        _temp_5 = -0.0858909963604649;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 1))  {
        _temp_5 = 0.363711685084048;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 2))  {
        _temp_5 = -0.277820688723583;
    }
    if (jmp.numeq(indata["Sex (M=1, F=2)"], 1))  {
        _temp_6 = 0.0590326968733491;
    }
    else if (jmp.numeq(indata["Sex (M=1, F=2)"], 2))  {
        _temp_6 = -0.0590326968733491;
    }
    if (jmp.numeq(TMZ_anytime_2_2_asCode, 0))  {
        _temp_7 = -0.147700954813856;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 1))  {
        _temp_7 = 0.717882687339312;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 2))  {
        _temp_7 = -1.12107271375258;
    }
    if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 0))  {
        _temp_8 = 0.0415265562816083;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 1))  {
        _temp_8 = 0.464122110935171;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 2))  {
        _temp_8 = -0.292052566652258;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 3))  {
        _temp_8 = 0.136804358317938;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 4))  {
        _temp_8 = -0.498351967812201;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 5))  {
        _temp_8 = 0.224023851055555;
    }
    if (jmp.numeq(WHO_Grade_2_2_asCode, 0))  {
        _temp_9 = 0.199259928705919;
    }
    else if (jmp.numeq(WHO_Grade_2_2_asCode, 1))  {
        _temp_9 = -0.199259928705919;
    }
    H1_1_1 = Math.tanh((-0.189498065818138 + -0.136904716750545 * Math.log(((-11.6322367884617 + indata["Age.at.Initial.Diagnosis"]) / (89.6435132764535 + -1 * indata["Age.at.Initial.Diagnosis"]))) + 0.5 * _temp_0 + 0.5 * _temp_1 + 0.5 * _temp_2 + 0.5 * _temp_3 + 0.5 * _temp_4 + 0.5 * _temp_5 + 0.5 * _temp_6 + 0.5 * _temp_7 + 0.5 * _temp_8 + 0.5 * _temp_9));

    if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 0))  {
        _temp_0 = 0.0237751112382746;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 1))  {
        _temp_0 = -0.119589881112571;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 2))  {
        _temp_0 = -0.183179258405319;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 3))  {
        _temp_0 = 0.278994028279615;
    }
    if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 0))  {
        _temp_1 = -0.131032016083515;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 1))  {
        _temp_1 = -0.359562198567442;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 2))  {
        _temp_1 = 0.490594214650958;
    }
    if (jmp.numeq(KPS_post_op_3_asCode, 0))  {
        _temp_2 = 0.190000047886121;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 1))  {
        _temp_2 = -0.0484618028676944;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 2))  {
        _temp_2 = 0.219577572600708;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 3))  {
        _temp_2 = 0.00718714258914292;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 4))  {
        _temp_2 = -0.368302960208278;
    }
    if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 0))  {
        _temp_3 = -0.164054667221055;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 1))  {
        _temp_3 = 0.182293098070574;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 2))  {
        _temp_3 = 0.135335128633339;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 3))  {
        _temp_3 = -0.234827889355386;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 4))  {
        _temp_3 = -0.0994536362975358;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 5))  {
        _temp_3 = -0.102905094750491;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 6))  {
        _temp_3 = -0.00472370540554088;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 7))  {
        _temp_3 = 0.288336766326095;
    }
    if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 0))  {
        _temp_4 = 0.0806764382980865;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 1))  {
        _temp_4 = 0.0334894985200525;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 2))  {
        _temp_4 = -0.211065949272443;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 3))  {
        _temp_4 = -0.107682953711725;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 4))  {
        _temp_4 = 0.20458296616603;
    }
    if (jmp.numeq(Seizure_preop_2_asCode, 0))  {
        _temp_5 = 0.0818806730585049;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 1))  {
        _temp_5 = -0.00975352005849766;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 2))  {
        _temp_5 = -0.0721271530000072;
    }
    if (jmp.numeq(indata["Sex (M=1, F=2)"], 1))  {
        _temp_6 = -0.11444723670835;
    }
    else if (jmp.numeq(indata["Sex (M=1, F=2)"], 2))  {
        _temp_6 = 0.11444723670835;
    }
    if (jmp.numeq(TMZ_anytime_2_2_asCode, 0))  {
        _temp_7 = -0.187226401615305;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 1))  {
        _temp_7 = -0.399366198064987;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 2))  {
        _temp_7 = 0.586592599680291;
    }
    if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 0))  {
        _temp_8 = -0.058617641093508;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 1))  {
        _temp_8 = -0.0752113924935183;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 2))  {
        _temp_8 = -0.0460104385486842;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 3))  {
        _temp_8 = 0.0357853850388711;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 4))  {
        _temp_8 = -0.0397828965390418;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 5))  {
        _temp_8 = 0.0797642102362243;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 6))  {
        _temp_8 = 0.104072773399657;
    }
    if (jmp.numeq(WHO_Grade_2_2_asCode, 0))  {
        _temp_9 = 0.0559314007858544;
    }
    else if (jmp.numeq(WHO_Grade_2_2_asCode, 1))  {
        _temp_9 = -0.0559314007858544;
    }
    H1_2_1 = Math.tanh((-0.0762627977271408 + 0.0205871086830134 * Math.log(((-11.6322367884617 + indata["Age.at.Initial.Diagnosis"]) / (89.6435132764535 + -1 * indata["Age.at.Initial.Diagnosis"]))) + 0.5 * _temp_0 + 0.5 * _temp_1 + 0.5 * _temp_2 + 0.5 * _temp_3 + 0.5 * _temp_4 + 0.5 * _temp_5 + 0.5 * _temp_6 + 0.5 * _temp_7 + 0.5 * _temp_8 + 0.5 * _temp_9));

    if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 0))  {
        _temp_0 = -0.274391997392284;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 1))  {
        _temp_0 = -0.362759186992472;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 2))  {
        _temp_0 = -1.0173215790521;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 3))  {
        _temp_0 = 1.65447276343685;
    }
    if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 0))  {
        _temp_1 = 0.986879199948826;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 1))  {
        _temp_1 = -0.807530978341589;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 2))  {
        _temp_1 = -0.179348221607237;
    }
    if (jmp.numeq(KPS_post_op_3_asCode, 0))  {
        _temp_2 = 0.549090180917342;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 1))  {
        _temp_2 = -0.892321926555133;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 2))  {
        _temp_2 = -0.223886256489678;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 3))  {
        _temp_2 = -0.666228635193291;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 4))  {
        _temp_2 = 1.23334663732076;
    }
    if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 0))  {
        _temp_3 = 0.872022634275439;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 1))  {
        _temp_3 = -0.214358708566012;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 2))  {
        _temp_3 = -0.502685692409063;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 3))  {
        _temp_3 = 0.115797173173299;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 4))  {
        _temp_3 = -0.670341348809547;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 5))  {
        _temp_3 = -0.162209768510826;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 6))  {
        _temp_3 = -0.679852740485696;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 7))  {
        _temp_3 = 1.24162845133241;
    }
    if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 0))  {
        _temp_4 = 0.290835126079727;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 1))  {
        _temp_4 = 1.97019657368995;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 2))  {
        _temp_4 = 0.28495294381258;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 3))  {
        _temp_4 = -1.30073194886369;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 4))  {
        _temp_4 = -1.24525269471857;
    }
    if (jmp.numeq(Seizure_preop_2_asCode, 0))  {
        _temp_5 = 0.303831848795258;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 1))  {
        _temp_5 = 0.778504940109571;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 2))  {
        _temp_5 = -1.08233678890483;
    }
    if (jmp.numeq(indata["Sex (M=1, F=2)"], 1))  {
        _temp_6 = -0.502300916088885;
    }
    else if (jmp.numeq(indata["Sex (M=1, F=2)"], 2))  {
        _temp_6 = 0.502300916088885;
    }
    if (jmp.numeq(TMZ_anytime_2_2_asCode, 0))  {
        _temp_7 = 0.525874818193521;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 1))  {
        _temp_7 = 1.42348112177167;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 2))  {
        _temp_7 = -1.9493559399652;
    }
    if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 0))  {
        _temp_8 = -0.0713855519054636;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 1))  {
        _temp_8 = -0.252190609271348;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 2))  {
        _temp_8 = 0.439025944932664;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 3))  {
        _temp_8 = 0.162571019200463;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 4))  {
        _temp_8 = 0.943109708801401;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 5))  {
        _temp_8 = 0.575596153716508;
      }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 6))  {
        _temp_8 = -1.79672666547422;
    }
    if (jmp.numeq(WHO_Grade_2_2_asCode, 0))  {
        _temp_9 = 0.024778213755159;
    }
    else if (jmp.numeq(WHO_Grade_2_2_asCode, 1))  {
        _temp_9 = -0.024778213755159;
    }
    H1_3_1 = Math.tanh((1.94639019323218 + 0.121575394134246 * Math.log(((-11.6322367884617 + indata["Age.at.Initial.Diagnosis"]) / (89.6435132764535 + -1 * indata["Age.at.Initial.Diagnosis"]))) + 0.5 * _temp_0 + 0.5 * _temp_1 + 0.5 * _temp_2 + 0.5 * _temp_3 + 0.5 * _temp_4 + 0.5 * _temp_5 + 0.5 * _temp_6 + 0.5 * _temp_7 + 0.5 * _temp_8 + 0.5 * _temp_9));

    if (jmp.numeq(indata["Sex (M=1, F=2)"], 1))  {
        _temp_0 = 0.251897754580538;
    }
    else if (jmp.numeq(indata["Sex (M=1, F=2)"], 2))  {
        _temp_0 = -0.251897754580538;
    }
    if (jmp.numeq(WHO_Grade_2_2_asCode, 0))  {
        _temp_1 = -0.152612528599997;
    }
    else if (jmp.numeq(WHO_Grade_2_2_asCode, 1))  {
        _temp_1 = 0.152612528599997;
    }
    if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 0))  {
        _temp_2 = -0.31679469583994;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 1))  {
        _temp_2 = 0.105745617159407;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 2))  {
        _temp_2 = 0.211049078680539;
    }
    if (jmp.numeq(Seizure_preop_2_asCode, 0))  {
        _temp_3 = 0.124700905356773;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 1))  {
        _temp_3 = 0.0506312800301624;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 2))  {
        _temp_3 = -0.1753321853869361;
    }
    if (jmp.numeq(TMZ_anytime_2_2_asCode, 0))  {
        _temp_4 = -0.0398712860329319;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 1))  {
        _temp_4 = 0.45753474349506;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 2))  {
        _temp_4 = -0.417663457462128;
    }
    if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 0))  {
        _temp_5 = 0.791493576301139;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 1))  {
        _temp_5 = -0.0244513811856896;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 2))  {
        _temp_5 = 0.267432980339133;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 3))  {
        _temp_5 = -1.03447517545458;
    }
    if (jmp.numeq(KPS_post_op_3_asCode, 0))  {
        _temp_6 = 0.276669378678425;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 1))  {
        _temp_6 = 0.429437142111609;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 2))  {
        _temp_6 = 0.00124670811104491;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 3))  {
        _temp_6 = 0.751693087864806;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 4))  {
        _temp_6 = 0.51854784686064;
    }
    if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 0))  {
        _temp_7 = 0.276669378678425;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 1))  {
        _temp_7 = 0.429437142111609;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 2))  {
        _temp_7 = 0.00124670811104491;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 3))  {
        _temp_7 = 0.751693087864806;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 4))  {
        _temp_7 = -1.45904631676588;
    }
    if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 0))  {
        _temp_8 = 0.180067411094087;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 1))  {
        _temp_8 = 0.345059940985695;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 2))  {
        _temp_8 = 0.0615586138471504;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 3))  {
        _temp_8 = 0.0983543245901424;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 4))  {
        _temp_8 = 0.223322914290542;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 5))  {
        _temp_8 = 0.107344667525694;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 6))  {
        _temp_8 = -1.01570787233331;
    }
    if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 0))  {
        _temp_9 = 0.605762805549438;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 1))  {
        _temp_9 = 0.628440758570712;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 2))  {
        _temp_9 = 0.0770149347488965;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 3))  {
        _temp_9 = 0.706000804765214;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 4))  {
        _temp_9 = 0.277749921327802;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 5))  {
        _temp_9 = 0.204546339952245;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 6))  {
        _temp_9 = 0.416873528712535;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 7))  {
        _temp_9 = -2.91638909362684;
    }
    H1_4_1 = 0.372515969560646 + -0.523130741290663 * Math.log(((-11.6322367884617 + indata["Age.at.Initial.Diagnosis"]) / (89.6435132764535 + -1 * indata["Age.at.Initial.Diagnosis"]))) + _temp_0 + _temp_1 + _temp_2 + _temp_3 + _temp_4 + _temp_5 + _temp_6 + _temp_7 + _temp_8 + _temp_9;
    if (jmp.numeq(indata["Sex (M=1, F=2)"], 1))  {
        _temp_0 = 0.203233328371212;
    }
    else if (jmp.numeq(indata["Sex (M=1, F=2)"], 2))  {
        _temp_0 = -0.203233328371212;
    }
    if (jmp.numeq(WHO_Grade_2_2_asCode, 0))  {
        _temp_1 = -0.140530898846548;
    }
    else if (jmp.numeq(WHO_Grade_2_2_asCode, 1))  {
        _temp_1 = 0.140530898846548;
    }
    if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 0))  {
        _temp_2 = -0.486085778920368;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 1))  {
        _temp_2 = 0.199933270603037;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 2))  {
        _temp_2 = 0.286152508317331;
 
    }
    if (jmp.numeq(Seizure_preop_2_asCode, 0))  {
        _temp_3 = 0.288971612738222;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 1))  {
        _temp_3 = 0.289212085756129;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 2))  {
        _temp_3 = -0.578183698494351;
    }
    if (jmp.numeq(TMZ_anytime_2_2_asCode, 0))  {
        _temp_4 = -0.0441207708425739;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 1))  {
        _temp_4 = 0.424638172031326;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 2))  {
        _temp_4 = -0.380517401188752;
    }
    if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 0))  {
        _temp_5 = 0.547588579619555;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 1))  {
        _temp_5 = -0.265238755566426;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 2))  {
        _temp_5 = 0.20063387266368;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 3))  {
        _temp_5 = -0.482983696716809;
    }
    if (jmp.numeq(KPS_post_op_3_asCode, 0))  {
        _temp_6 = -0.426967966506797;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 1))  {
        _temp_6 = -0.271214800334523;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 2))  {
        _temp_6 = -0.263626728181577;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 3))  {
        _temp_6 = 0.00831109536880886;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 4))  {
        _temp_6 = 0.953498399654088;
    }
    if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 0))  {
        _temp_7 = 0.191027923498925;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 1))  {
        _temp_7 = 0.479066849899603;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 2))  {
        _temp_7 = 0.13697894778609;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 3))  {
        _temp_7 = 0.641996503520577;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 4))  {
        _temp_7 = -1.4490702247052;
    }
    if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 0))  {
        _temp_8 = 0.105592489705452;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 1))  {
        _temp_8 = 0.157501427686568;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 2))  {
        _temp_8 = 0.0738151860938904;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 3))  {
        _temp_8 = 0.12657191641808;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 4))  {
        _temp_8 = 0.170136881255706;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 5))  {
        _temp_8 = 0.0547920789245792;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 6))  {
        _temp_8 = -0.688409980084275;
    }
    if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 0))  {
        _temp_9 = 0.381994272938961;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 1))  {
        _temp_9 = -0.0389387255990775;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 2))  {
        _temp_9 = 0.0220987091611338;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 3))  {
        _temp_9 = 0.507904685716836;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 4))  {
        _temp_9 = 0.235228302077014;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 5))  {
        _temp_9 = 0.139342351292817;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 6))  {
        _temp_9 = 0.180364543226395;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 7))  {
        _temp_9 = -1.42799413881408;
    }
    H1_5_1 = 0.419465453290747 + -0.325450398436629 * Math.log(((-11.6322367884617 + indata["Age.at.Initial.Diagnosis"]) / (89.6435132764535 + -1 * indata["Age.at.Initial.Diagnosis"]))) + _temp_0 + _temp_1 + _temp_2 + _temp_3 + _temp_4 + _temp_5 + _temp_6 + _temp_7 + _temp_8 + _temp_9;

    if (jmp.numeq(indata["Sex (M=1, F=2)"], 1))  {
        _temp_0 = 0.133516833393547;
    }
    else if (jmp.numeq(indata["Sex (M=1, F=2)"], 2))  {
        _temp_0 = -0.133516833393547;
    }
    if (jmp.numeq(WHO_Grade_2_2_asCode, 0))  {
        _temp_1 = -0.0336622677703033;
    }
    else if (jmp.numeq(WHO_Grade_2_2_asCode, 1))  {
        _temp_1 = 0.033662267770303;
    }
    if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 0))  {
        _temp_2 = -0.24642491163728;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 1))  {
        _temp_2 = 0.16129226070738;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 2))  {
        _temp_2 = 0.0851326509299003;
    }
    if (jmp.numeq(Seizure_preop_2_asCode, 0))  {
        _temp_3 = 0.221376442407133;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 1))  {
        _temp_3 = 0.288347323103581;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 2))  {
        _temp_3 = -0.509723765510714;
    }
    if (jmp.numeq(TMZ_anytime_2_2_asCode, 0))  {
        _temp_4 = -0.0144714382425054;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 1))  {
        _temp_4 = 0.169378534432977;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 2))  {
        _temp_4 = -0.15490709619047;
    }
    if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 0))  {
        _temp_5 = 0.0067481196361444;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 1))  {
        _temp_5 = -0.18033924647579;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 2))  {
        _temp_5 = 0.0358110854240114;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 3))  {
        _temp_5 = 0.137780041415634;
    }
    if (jmp.numeq(KPS_post_op_3_asCode, 0))  {
        _temp_6 = -0.0231670913960045;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 1))  {
        _temp_6 = -0.0980383578886601;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 2))  {
        _temp_6 = 0.19048300188306;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 3))  {
        _temp_6 = -0.0782172290693212;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 4))  {
        _temp_6 = 0.389905680237046;
    }
    if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 0))  {
        _temp_7 = 0.0136071263941615;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 1))  {
        _temp_7 = 0.335078989209813;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 2))  {
        _temp_7 = 0.149633813130174;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 3))  {
        _temp_7 = 0.150296158398846;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 4))  {
        _temp_7 = -0.648616087132995;
    }
    if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 0))  {
        _temp_8 = -0.0599133088163611;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 1))  {
        _temp_8 = -0.125417548213399;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 2))  {
        _temp_8 = 0.0588605257062206;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 3))  {
        _temp_8 = 0.0351736522976984;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 4))  {
        _temp_8 = 0.0428760299583367;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 5))  {
        _temp_8 = -0.0599235427515109;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 6))  {
        _temp_8 = 0.108344191819015;
    }
    if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 0))  {
        _temp_9 = -0.493219300299262;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 1))  {
        _temp_9 = 0.0557022433483314;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 2))  {
        _temp_9 = -0.00551720816861426;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 3))  {
        _temp_9 =  0.0103492349549222;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 4))  {
        _temp_9 = 0.133717235842985;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 5))  {
        _temp_9 = -0.052343509777323;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 6))  {
        _temp_9 = -0.00727967132368769;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 7))  {
        _temp_9 = 0.42595782442234;
    }
    H1_6_1 = 0.0359463840909912 + -0.00550251935620229 * Math.log(((-11.6322367884617 + indata["Age.at.Initial.Diagnosis"]) / (89.6435132764535 + -1 * indata["Age.at.Initial.Diagnosis"]))) + _temp_0 + _temp_1 + _temp_2 + _temp_3 + _temp_4 + _temp_5 + _temp_6 + _temp_7 + _temp_8 + _temp_9;

    if (jmp.numeq(indata["Sex (M=1, F=2)"], 1))  {
        _temp_0 = -0.0577612124900942;
    }
    else if (jmp.numeq(indata["Sex (M=1, F=2)"], 2))  {
        _temp_0 = 0.0577612124900942;
    }
    if (jmp.numeq(WHO_Grade_2_2_asCode, 0))  {
        _temp_1 = 0.124025251540017;
    }
    else if (jmp.numeq(WHO_Grade_2_2_asCode, 1))  {
        _temp_1 = -0.124025251540017;
    }
    if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 0))  {
        _temp_2 = -1.11953749043308;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 1))  {
        _temp_2 = 0.644313107459744;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 2))  {
        _temp_2 = 0.475224382973341;
    }
    if (jmp.numeq(Seizure_preop_2_asCode, 0))  {
        _temp_3 = -0.0969480525914383;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 1))  {
        _temp_3 = 0.929072886526392;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 2))  {
        _temp_3 = -0.832124833934954;
    }
    if (jmp.numeq(TMZ_anytime_2_2_asCode, 0))  {
        _temp_4 = -0.182373702889428;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 1))  {
        _temp_4 = -0.644432558996541;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 2))  {
        _temp_4 = 0.826806261885968;
    }
    if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 0))  {
        _temp_5 = 1.10163793356367;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 1))  {
        _temp_6 = -1.2246560443532;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 2))  {
        _temp_5 = 0.313040425606567;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 3))  {
        _temp_5 = -0.190022314817042;
    }
    if (jmp.numeq(KPS_post_op_3_asCode, 0))  {
        _temp_6 = -0.898649691214404;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 1))  {
        _temp_6 = 0.30519999125091;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 2))  {
        _temp_6 = 0.254838623598317;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 3))  {
        _temp_6 = 0.10968379465957;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 4))  {
        _temp_6 = 0.228927281705607;
    }
    if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 0))  {
        _temp_7 = -0.0223826486587303;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 1))  {
        _temp_7 = -0.93791442534631;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 2))  {
        _temp_7 = -0.395702885172414;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 3))  {
        _temp_7 = 1.97003022209183;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 4))  {
        _temp_7 = -0.614030262914378;
    }
    if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 0))  {
        _temp_8 = -0.806583742161181;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 1))  {
        _temp_8 = 0.15367237775351;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 2))  {
        _temp_8 = -0.581948229581336;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 3))  {
        _temp_8 = -1.13142461754078;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 4))  {
        _temp_8 = -0.782030342724537;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 5))  {
        _temp_8 = -0.523115081413824;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 6))  {
        _temp_8 = 3.67142963566815;
    }
    if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 0))  {
        _temp_9 = -0.0538659281753216;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 1))  {
        _temp_9 = 1.39143404845885;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 2))  {
        _temp_9 = 0.372245982153168;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 3))  {
        _temp_9 = 1.24923835368529;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 4))  {
        _temp_9 = -0.419317506852587;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 5))  {
        _temp_9 = 0.769493129602178;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 6))  {
        _temp_9 = -0.579048829744727;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 7))  {
        _temp_9 = -2.73017924912685;
    }
   H1_7_1 = Math.exp(-((0.5 * Math.pow((-4.35958256077917 + -1.08919185949274 * Math.log(((-11.6322367884617 + indata["Age.at.Initial.Diagnosis"]) / (89.6435132764535 + -1 * indata["Age.at.Initial.Diagnosis"]))) + _temp_0 + _temp_1 + _temp_2 + _temp_3 + _temp_4 + _temp_5 + _temp_6 + _temp_7 + _temp_8 + _temp_9), 2))));

    if (jmp.numeq(indata["Sex (M=1, F=2)"], 1))  {
        _temp_0 = -0.21788288518443;
    }
    else if (jmp.numeq(indata["Sex (M=1, F=2)"], 2))  {
        _temp_0 = 0.21788288518443;
    }
    if (jmp.numeq(WHO_Grade_2_2_asCode, 0))  {
        _temp_1 = 0.496505922571509;
    }
    else if (jmp.numeq(WHO_Grade_2_2_asCode, 1))  {
        _temp_1 = -0.496505922571509;
    }
    if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 0))  {
        _temp_2 = 0.341784591269466;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 1))  {
        _temp_2 = -0.931325852462107;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 2))  {
        _temp_2 = 0.589541261192641;
    }
    if (jmp.numeq(Seizure_preop_2_asCode, 0))  {
        _temp_3 = -0.994323627840753;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 1))  {
        _temp_3 = 0.287073828553811;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 2))  {
        _temp_3 = 0.707249799286942;
    }
    if (jmp.numeq(TMZ_anytime_2_2_asCode, 0))  {
        _temp_4 = 0.648073338249544;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 1))  {
        _temp_4 = -0.690780666934527;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 2))  {
        _temp_4 = 0.0427073286849825;
    }
    if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 0))  {
        _temp_5 = -0.521781766115371;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 1))  {
        _temp_5 = 1.01739392918978;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 2))  {
        _temp_5 = 1.19441458986446;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 3))  {
        _temp_5 = -1.69002675293887;
    }
    if (jmp.numeq(KPS_post_op_3_asCode, 0))  {
        _temp_6 = 0.325386548344933;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 1))  {
        _temp_6 = -0.492302745360655;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 2))  {
        _temp_6 = 1.09403921678708;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 3))  {
        _temp_6 = 0.955902181419083;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 4))  {
        _temp_6 = -1.88302520119044;
    }
    if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 0))  {
        _temp_7 = 0.23911557675073;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 1))  {
        _temp_7 = -0.0468150684350184;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 2))  {
        _temp_7 = -0.757986674678707;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 3))  {
        _temp_7 = 0.267494498826834;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 4))  {
        _temp_7 = 0.298191667536161;
    }
    if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 0))  {
        _temp_8 = -0.331121401463314;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 1))  {
        _temp_8 = 0.782002028689726;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 2))  {
        _temp_8 = -0.361608744441757;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 3))  {
        _temp_8 = 0.580391776565729;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 4))  {
        _temp_8 = -0.552972229620858;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 5))  {
        _temp_8 = 0.46643678937564;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 6))  {
        _temp_8 = -0.5831282191051664;
    }
    if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 0))  {
        _temp_9 = 1.697108174886664;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 1))  {
        _temp_9 = -0.1056956272640267;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 2))  {
        _temp_9 = 0.26746636774194;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 3))  {
        _temp_9 = -0.63389705970549;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 4))  {
        _temp_9 = 0.365281126572475;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 5))  {
        _temp_9 = -0.00549910577320459;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 6))  {
        _temp_9 = -1.29144942782032;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 7))  {
        _temp_9 = -0.293314448638035;
    }
    H1_8_1 = Math.exp(-((0.5 * Math.pow((1.27765415756494 + 0.235787509260951 * Math.log(((-11.6322367884617 + indata["Age.at.Initial.Diagnosis"]) / (89.6435132764535 + -1 * indata["Age.at.Initial.Diagnosis"]))) + _temp_0 + _temp_1 + _temp_2 + _temp_3 + _temp_4 + _temp_5 + _temp_6 + _temp_7 + _temp_8 + _temp_9), 2))));

    if (jmp.numeq(indata["Sex (M=1, F=2)"], 1))  {
        _temp_0 = -0.20260034099646;
    }
    else if (jmp.numeq(indata["Sex (M=1, F=2)"], 2))  {
        _temp_0 = 0.20260034099646;
    }
    if (jmp.numeq(WHO_Grade_2_2_asCode, 0))  {
        _temp_1 = 0.197514266786602;
    }
    else if (jmp.numeq(WHO_Grade_2_2_asCode, 1))  {
        _temp_1 = -0.197514266786602;
    }
    if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 0))  {
        _temp_2 = 0.862016857987336;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 1))  {
        _temp_2 = -0.636283581205481;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 2))  {
        _temp_2 = -0.225733276781856;
    }
    if (jmp.numeq(Seizure_preop_2_asCode, 0))  {
        _temp_3 = -1.47339459072853;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 1))  {
        _temp_3 = 0.584635532911111;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 2))  {
        _temp_3 = 0.888759057817415;
    }
    if (jmp.numeq(TMZ_anytime_2_2_asCode, 0))  {
        _temp_4 = 1.21582370005879;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 1))  {
        _temp_4 = 0.536672449619317;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 2))  {
        _temp_4 = -1.75249614967811;
    }
    if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 0))  {
        _temp_5 = 0.053730748195506;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 1))  {
        _temp_5 = -0.920824895214651;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 2))  {
        _temp_5 = 0.035520831845533;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 3))  {
        _temp_5 = 0.831573315173612;
    }
    if (jmp.numeq(KPS_post_op_3_asCode, 0))  {
        _temp_6 =0.513660782969264;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 1))  {
        _temp_6 = 0.268121345281344;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 2))  {
        _temp_6 = -0.333896884569215;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 3))  {
        _temp_6 = -0.93748876843055;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 4))  {
        _temp_6 = 0.489603524749162;
    }
    if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 0))  {
        _temp_7 = -1.45702574284349;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 1))  {
        _temp_7 = -0.66693405548903;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 2))  {
        _temp_7 = -0.123608646905729;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 3))  {
        _temp_7 = -2.15452615644934;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 4))  {
        _temp_7 = 4.40209460168759;
    }
    if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 0))  {
        _temp_8 = -0.449557985157274;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 1))  {
        _temp_8 = 0.0939738731099869;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 2))  {
        _temp_8 = 0.792417627820648;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 3))  {
        _temp_8 = 0.181962929931391;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 4))  {
        _temp_8 = -0.982482392775062;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 5))  {
        _temp_8 = 0.275860015620587;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 6))  {
        _temp_8 = 0.0878259314497241;
    }
    if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 0))  {
        _temp_9 = 1.07406634313454;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 1))  {
        _temp_9 = -1.3417912186540;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 2))  {
        _temp_9 = -1.21055497321659;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 3))  {
        _temp_9 = 0.636643338137167;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 4))  {
        _temp_9 = -1.66728327334692;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 5))  {
        _temp_9 = -0.179731170537166;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 6))  {
        _temp_9 = -0.0333527806294852;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 7))  {
        _temp_9 = 2.72200373511252;
    }
   H1_9_1 = Math.exp(-((0.5 * Math.pow((2.22097804328749 + -0.690691704984242 * Math.log(((-11.6322367884617 + indata["Age.at.Initial.Diagnosis"]) / (89.6435132764535 + -1 * indata["Age.at.Initial.Diagnosis"]))) + _temp_0 + _temp_1 + _temp_2 + _temp_3 + _temp_4 + _temp_5 + _temp_6 + _temp_7 + _temp_8 + _temp_9), 2))));

    outdata["Probability( Clinical Trial enrollment: (Yes=1, No =2)=1 )_1"] = Math.exp((-0.273226016563953 + -1.80645679442871 * H1_1_1 + -0.778954706085276 * H1_2_1 + -1.89821124716246 * H1_3_1 + 0.31496750476159 * H1_4_1 + 0.561220256058835 * H1_5_1 + 0.530126799500854 * H1_6_1 + 1.18319822352502 * H1_7_1 + -1.66722221579876 * H1_8_1 + -1.82863696757146 * H1_9_1)) / (1 + Math.exp((-0.273226016563953 + -1.80645679442871 * H1_1_1 + -0.778954706085276 * H1_2_1 + -1.89821124716246 * H1_3_1 + 0.31496750476159 * H1_4_1 + 0.561220256058835 * H1_5_1 + 0.530126799500854 * H1_6_1 + 1.18319822352502 * H1_7_1 + -1.66722221579876 * H1_8_1 + -1.82863696757146 * H1_9_1)));

    outdata["Probability( Clinical Trial enrollment: (Yes=1, No =2)=2 )_1"] = 1 / (1 + Math.exp((-0.273226016563953 + -1.80645679442871 * H1_1_1 + -0.778954706085276 * H1_2_1 + -1.89821124716246 * H1_3_1 + 0.31496750476159 * H1_4_1 + 0.561220256058835 * H1_5_1 + 0.530126799500854 * H1_6_1 + 1.18319822352502 * H1_7_1 + -1.66722221579876 * H1_8_1 + -1.82863696757146 * H1_9_1)));
    _temp_11[0] = outdata["ProbabilityEnroll"];
    _temp_11[1] = outdata["ProbabilityNotEnroll"];
    _temp_10 = jmp.max_array(2, _temp_11);
    switch (_temp_10) {
        case 0: {
            _temp_0 = 1;
        }
        break;
        case 1: {
            _temp_0 = 2;
        }
        break;
        default: {
            _temp_0 = undefined;
        }
    }
    outdata["MostLikelyClinicalTrial"] = _temp_0;

    return outdata["MostLikelyClinicalTrial"];
};
console.log(typeof score);
